### PR TITLE
Basic Operations

### PR DESCRIPTION
**Pull request by tortmann**
As explained in my commit details/comments I implemented the basic structure for the remaining calculation operations so the respective groups can start working on this. This is also the reason why I am sending you this pull request so we can now focus on the implementation in the patter matching of the main operations functions.

### CODE REVIEW

**Comment by tortmann** [comment]
I also added the implementation for the missing basic operations minus multi and div - sry for the extra commit I hope this is automatically added to my previous pull request. I didnt realize that the implementation was that simple and I would be finished that quickly

**Comment by tortmann** [comment]
case PERCENTAGE - implemented

**Comment by tortmann** [comment]
added CLEAR and COMMA, and started with the divsion by zero error handling, my result is now Infinity - displayed in the GUI but i get the output of the if clause in the console so my if statement implementation should be correct but not the displaying of the message. i need to override the output " Infinity"

**Comment by tortmann** [comment]
division by zero error handling inlucing the correct output is now implemented as well

**Comment by tortmann** [comment]
Added A. Bajric' implementation of case CLEAR to have a complete package for the pull request

**Comment by rladstaetter** [comment]
will merge this this evening ...

**Comment by rladstaetter** [comment]
merged, thank you!

**Comment by tortmann** [comment]
thank you for merging, now we can tackle the remaining problems as groups more easily. I hope the implementation meets the requirements.to give you a little feedback - right now I am in the middle of properly organizing how we work on this project in the future ( only pull requests from group leaders, using the issue funcitonality of github etc.)

**Comment by rladstaetter** [comment]
great! i would advise that you merge the commits first in your fork, and after that you send a combined pull request

**Comment by tortmann** [comment]
okay thank you for the tip! have a nice evening

**Pull request merged**
