### PR TITLE
implemented the CLEAR function

### PR DESCRIPTION
**Pull request by amarbajric**
I already have got the pull request changes from Mr. Ortmann and then I have implemented the 
CLEAR "C" function!

### CODE REVIEW

**Comment by rladstaetter** [comment]
will merge this this evening ...

**Comment by rladstaetter** [comment]
clear is already on the main branch, please coordinate with tortmann / knaller / fuchs.

**Comment by amarbajric** [comment]
Dear Mr. Ladstätter,

Its okay since tortmann merged my Clear function to his PR!!

Best regards,
Bajric Amar

**Comment by rladstaetter** [comment]
ok, perfect.

**Pull request closed without merging**
